// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: room_manager/room_manager.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_room_manager_room_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_manager_room_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_room_manager_room_manager_proto_rawDescGZIP(), []int{0}
}

func (x *PingResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type PingWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Worker        string                 `protobuf:"bytes,1,opt,name=worker,proto3" json:"worker,omitempty"`
	LoadedRooms   []string               `protobuf:"bytes,2,rep,name=loaded_rooms,json=loadedRooms,proto3" json:"loaded_rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingWorkerRequest) Reset() {
	*x = PingWorkerRequest{}
	mi := &file_room_manager_room_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingWorkerRequest) ProtoMessage() {}

func (x *PingWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_manager_room_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingWorkerRequest.ProtoReflect.Descriptor instead.
func (*PingWorkerRequest) Descriptor() ([]byte, []int) {
	return file_room_manager_room_manager_proto_rawDescGZIP(), []int{1}
}

func (x *PingWorkerRequest) GetWorker() string {
	if x != nil {
		return x.Worker
	}
	return ""
}

func (x *PingWorkerRequest) GetLoadedRooms() []string {
	if x != nil {
		return x.LoadedRooms
	}
	return nil
}

type GetRoomWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomWorkerRequest) Reset() {
	*x = GetRoomWorkerRequest{}
	mi := &file_room_manager_room_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomWorkerRequest) ProtoMessage() {}

func (x *GetRoomWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_manager_room_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomWorkerRequest.ProtoReflect.Descriptor instead.
func (*GetRoomWorkerRequest) Descriptor() ([]byte, []int) {
	return file_room_manager_room_manager_proto_rawDescGZIP(), []int{2}
}

func (x *GetRoomWorkerRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type GetRoomWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Worker        string                 `protobuf:"bytes,1,opt,name=worker,proto3" json:"worker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomWorkerResponse) Reset() {
	*x = GetRoomWorkerResponse{}
	mi := &file_room_manager_room_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomWorkerResponse) ProtoMessage() {}

func (x *GetRoomWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_manager_room_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomWorkerResponse.ProtoReflect.Descriptor instead.
func (*GetRoomWorkerResponse) Descriptor() ([]byte, []int) {
	return file_room_manager_room_manager_proto_rawDescGZIP(), []int{3}
}

func (x *GetRoomWorkerResponse) GetWorker() string {
	if x != nil {
		return x.Worker
	}
	return ""
}

type RegisterRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Worker        string                 `protobuf:"bytes,2,opt,name=worker,proto3" json:"worker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRoomRequest) Reset() {
	*x = RegisterRoomRequest{}
	mi := &file_room_manager_room_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRoomRequest) ProtoMessage() {}

func (x *RegisterRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_manager_room_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRoomRequest.ProtoReflect.Descriptor instead.
func (*RegisterRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_manager_room_manager_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RegisterRoomRequest) GetWorker() string {
	if x != nil {
		return x.Worker
	}
	return ""
}

type RegisterRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Worker        string                 `protobuf:"bytes,1,opt,name=worker,proto3" json:"worker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRoomResponse) Reset() {
	*x = RegisterRoomResponse{}
	mi := &file_room_manager_room_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRoomResponse) ProtoMessage() {}

func (x *RegisterRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_manager_room_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRoomResponse.ProtoReflect.Descriptor instead.
func (*RegisterRoomResponse) Descriptor() ([]byte, []int) {
	return file_room_manager_room_manager_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterRoomResponse) GetWorker() string {
	if x != nil {
		return x.Worker
	}
	return ""
}

type ProlongRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Worker        string                 `protobuf:"bytes,2,opt,name=worker,proto3" json:"worker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProlongRoomRequest) Reset() {
	*x = ProlongRoomRequest{}
	mi := &file_room_manager_room_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProlongRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProlongRoomRequest) ProtoMessage() {}

func (x *ProlongRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_manager_room_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProlongRoomRequest.ProtoReflect.Descriptor instead.
func (*ProlongRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_manager_room_manager_proto_rawDescGZIP(), []int{6}
}

func (x *ProlongRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ProlongRoomRequest) GetWorker() string {
	if x != nil {
		return x.Worker
	}
	return ""
}

type ReleaseRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Worker        string                 `protobuf:"bytes,2,opt,name=worker,proto3" json:"worker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRoomRequest) Reset() {
	*x = ReleaseRoomRequest{}
	mi := &file_room_manager_room_manager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRoomRequest) ProtoMessage() {}

func (x *ReleaseRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_manager_room_manager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRoomRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_manager_room_manager_proto_rawDescGZIP(), []int{7}
}

func (x *ReleaseRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ReleaseRoomRequest) GetWorker() string {
	if x != nil {
		return x.Worker
	}
	return ""
}

var File_room_manager_room_manager_proto protoreflect.FileDescriptor

const file_room_manager_room_manager_proto_rawDesc = "" +
	"\n" +
	"\x1froom_manager/room_manager.proto\x12\froom_manager\x1a\x1bgoogle/protobuf/empty.proto\"\x1e\n" +
	"\fPingResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"N\n" +
	"\x11PingWorkerRequest\x12\x16\n" +
	"\x06worker\x18\x01 \x01(\tR\x06worker\x12!\n" +
	"\floaded_rooms\x18\x02 \x03(\tR\vloadedRooms\"/\n" +
	"\x14GetRoomWorkerRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"/\n" +
	"\x15GetRoomWorkerResponse\x12\x16\n" +
	"\x06worker\x18\x01 \x01(\tR\x06worker\"F\n" +
	"\x13RegisterRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x16\n" +
	"\x06worker\x18\x02 \x01(\tR\x06worker\".\n" +
	"\x14RegisterRoomResponse\x12\x16\n" +
	"\x06worker\x18\x01 \x01(\tR\x06worker\"E\n" +
	"\x12ProlongRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x16\n" +
	"\x06worker\x18\x02 \x01(\tR\x06worker\"E\n" +
	"\x12ReleaseRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x16\n" +
	"\x06worker\x18\x02 \x01(\tR\x06worker2\xda\x03\n" +
	"\x12RoomManagerService\x12:\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x1a.room_manager.PingResponse\x12X\n" +
	"\rGetRoomWorker\x12\".room_manager.GetRoomWorkerRequest\x1a#.room_manager.GetRoomWorkerResponse\x12E\n" +
	"\n" +
	"PingWorker\x12\x1f.room_manager.PingWorkerRequest\x1a\x16.google.protobuf.Empty\x12U\n" +
	"\fRegisterRoom\x12!.room_manager.RegisterRoomRequest\x1a\".room_manager.RegisterRoomResponse\x12G\n" +
	"\vProlongRoom\x12 .room_manager.ProlongRoomRequest\x1a\x16.google.protobuf.Empty\x12G\n" +
	"\vReleaseRoom\x12 .room_manager.ReleaseRoomRequest\x1a\x16.google.protobuf.EmptyB.Z,github.com/xolra0d/alias-online/shared/protob\x06proto3"

var (
	file_room_manager_room_manager_proto_rawDescOnce sync.Once
	file_room_manager_room_manager_proto_rawDescData []byte
)

func file_room_manager_room_manager_proto_rawDescGZIP() []byte {
	file_room_manager_room_manager_proto_rawDescOnce.Do(func() {
		file_room_manager_room_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_room_manager_room_manager_proto_rawDesc), len(file_room_manager_room_manager_proto_rawDesc)))
	})
	return file_room_manager_room_manager_proto_rawDescData
}

var file_room_manager_room_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_room_manager_room_manager_proto_goTypes = []any{
	(*PingResponse)(nil),          // 0: room_manager.PingResponse
	(*PingWorkerRequest)(nil),     // 1: room_manager.PingWorkerRequest
	(*GetRoomWorkerRequest)(nil),  // 2: room_manager.GetRoomWorkerRequest
	(*GetRoomWorkerResponse)(nil), // 3: room_manager.GetRoomWorkerResponse
	(*RegisterRoomRequest)(nil),   // 4: room_manager.RegisterRoomRequest
	(*RegisterRoomResponse)(nil),  // 5: room_manager.RegisterRoomResponse
	(*ProlongRoomRequest)(nil),    // 6: room_manager.ProlongRoomRequest
	(*ReleaseRoomRequest)(nil),    // 7: room_manager.ReleaseRoomRequest
	(*emptypb.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_room_manager_room_manager_proto_depIdxs = []int32{
	8, // 0: room_manager.RoomManagerService.Ping:input_type -> google.protobuf.Empty
	2, // 1: room_manager.RoomManagerService.GetRoomWorker:input_type -> room_manager.GetRoomWorkerRequest
	1, // 2: room_manager.RoomManagerService.PingWorker:input_type -> room_manager.PingWorkerRequest
	4, // 3: room_manager.RoomManagerService.RegisterRoom:input_type -> room_manager.RegisterRoomRequest
	6, // 4: room_manager.RoomManagerService.ProlongRoom:input_type -> room_manager.ProlongRoomRequest
	7, // 5: room_manager.RoomManagerService.ReleaseRoom:input_type -> room_manager.ReleaseRoomRequest
	0, // 6: room_manager.RoomManagerService.Ping:output_type -> room_manager.PingResponse
	3, // 7: room_manager.RoomManagerService.GetRoomWorker:output_type -> room_manager.GetRoomWorkerResponse
	8, // 8: room_manager.RoomManagerService.PingWorker:output_type -> google.protobuf.Empty
	5, // 9: room_manager.RoomManagerService.RegisterRoom:output_type -> room_manager.RegisterRoomResponse
	8, // 10: room_manager.RoomManagerService.ProlongRoom:output_type -> google.protobuf.Empty
	8, // 11: room_manager.RoomManagerService.ReleaseRoom:output_type -> google.protobuf.Empty
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_room_manager_room_manager_proto_init() }
func file_room_manager_room_manager_proto_init() {
	if File_room_manager_room_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_room_manager_room_manager_proto_rawDesc), len(file_room_manager_room_manager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_room_manager_room_manager_proto_goTypes,
		DependencyIndexes: file_room_manager_room_manager_proto_depIdxs,
		MessageInfos:      file_room_manager_room_manager_proto_msgTypes,
	}.Build()
	File_room_manager_room_manager_proto = out.File
	file_room_manager_room_manager_proto_goTypes = nil
	file_room_manager_room_manager_proto_depIdxs = nil
}
