// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: room_manager/room_manager.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoomManagerService_Ping_FullMethodName          = "/room_manager.RoomManagerService/Ping"
	RoomManagerService_GetRoomWorker_FullMethodName = "/room_manager.RoomManagerService/GetRoomWorker"
	RoomManagerService_PingWorker_FullMethodName    = "/room_manager.RoomManagerService/PingWorker"
	RoomManagerService_RegisterRoom_FullMethodName  = "/room_manager.RoomManagerService/RegisterRoom"
	RoomManagerService_ProlongRoom_FullMethodName   = "/room_manager.RoomManagerService/ProlongRoom"
	RoomManagerService_ReleaseRoom_FullMethodName   = "/room_manager.RoomManagerService/ReleaseRoom"
)

// RoomManagerServiceClient is the client API for RoomManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoomManagerServiceClient interface {
	Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PingResponse, error)
	// for main service.
	GetRoomWorker(ctx context.Context, in *GetRoomWorkerRequest, opts ...grpc.CallOption) (*GetRoomWorkerResponse, error)
	// for workers.
	PingWorker(ctx context.Context, in *PingWorkerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RegisterRoom(ctx context.Context, in *RegisterRoomRequest, opts ...grpc.CallOption) (*RegisterRoomResponse, error)
	ProlongRoom(ctx context.Context, in *ProlongRoomRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReleaseRoom(ctx context.Context, in *ReleaseRoomRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type roomManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoomManagerServiceClient(cc grpc.ClientConnInterface) RoomManagerServiceClient {
	return &roomManagerServiceClient{cc}
}

func (c *roomManagerServiceClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, RoomManagerService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomManagerServiceClient) GetRoomWorker(ctx context.Context, in *GetRoomWorkerRequest, opts ...grpc.CallOption) (*GetRoomWorkerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoomWorkerResponse)
	err := c.cc.Invoke(ctx, RoomManagerService_GetRoomWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomManagerServiceClient) PingWorker(ctx context.Context, in *PingWorkerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RoomManagerService_PingWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomManagerServiceClient) RegisterRoom(ctx context.Context, in *RegisterRoomRequest, opts ...grpc.CallOption) (*RegisterRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterRoomResponse)
	err := c.cc.Invoke(ctx, RoomManagerService_RegisterRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomManagerServiceClient) ProlongRoom(ctx context.Context, in *ProlongRoomRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RoomManagerService_ProlongRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomManagerServiceClient) ReleaseRoom(ctx context.Context, in *ReleaseRoomRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RoomManagerService_ReleaseRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoomManagerServiceServer is the server API for RoomManagerService service.
// All implementations must embed UnimplementedRoomManagerServiceServer
// for forward compatibility.
type RoomManagerServiceServer interface {
	Ping(context.Context, *emptypb.Empty) (*PingResponse, error)
	// for main service.
	GetRoomWorker(context.Context, *GetRoomWorkerRequest) (*GetRoomWorkerResponse, error)
	// for workers.
	PingWorker(context.Context, *PingWorkerRequest) (*emptypb.Empty, error)
	RegisterRoom(context.Context, *RegisterRoomRequest) (*RegisterRoomResponse, error)
	ProlongRoom(context.Context, *ProlongRoomRequest) (*emptypb.Empty, error)
	ReleaseRoom(context.Context, *ReleaseRoomRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedRoomManagerServiceServer()
}

// UnimplementedRoomManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoomManagerServiceServer struct{}

func (UnimplementedRoomManagerServiceServer) Ping(context.Context, *emptypb.Empty) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedRoomManagerServiceServer) GetRoomWorker(context.Context, *GetRoomWorkerRequest) (*GetRoomWorkerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoomWorker not implemented")
}
func (UnimplementedRoomManagerServiceServer) PingWorker(context.Context, *PingWorkerRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PingWorker not implemented")
}
func (UnimplementedRoomManagerServiceServer) RegisterRoom(context.Context, *RegisterRoomRequest) (*RegisterRoomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterRoom not implemented")
}
func (UnimplementedRoomManagerServiceServer) ProlongRoom(context.Context, *ProlongRoomRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ProlongRoom not implemented")
}
func (UnimplementedRoomManagerServiceServer) ReleaseRoom(context.Context, *ReleaseRoomRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseRoom not implemented")
}
func (UnimplementedRoomManagerServiceServer) mustEmbedUnimplementedRoomManagerServiceServer() {}
func (UnimplementedRoomManagerServiceServer) testEmbeddedByValue()                            {}

// UnsafeRoomManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoomManagerServiceServer will
// result in compilation errors.
type UnsafeRoomManagerServiceServer interface {
	mustEmbedUnimplementedRoomManagerServiceServer()
}

func RegisterRoomManagerServiceServer(s grpc.ServiceRegistrar, srv RoomManagerServiceServer) {
	// If the following call panics, it indicates UnimplementedRoomManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoomManagerService_ServiceDesc, srv)
}

func _RoomManagerService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomManagerServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomManagerService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomManagerServiceServer).Ping(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomManagerService_GetRoomWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomManagerServiceServer).GetRoomWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomManagerService_GetRoomWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomManagerServiceServer).GetRoomWorker(ctx, req.(*GetRoomWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomManagerService_PingWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomManagerServiceServer).PingWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomManagerService_PingWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomManagerServiceServer).PingWorker(ctx, req.(*PingWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomManagerService_RegisterRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomManagerServiceServer).RegisterRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomManagerService_RegisterRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomManagerServiceServer).RegisterRoom(ctx, req.(*RegisterRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomManagerService_ProlongRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProlongRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomManagerServiceServer).ProlongRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomManagerService_ProlongRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomManagerServiceServer).ProlongRoom(ctx, req.(*ProlongRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomManagerService_ReleaseRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomManagerServiceServer).ReleaseRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomManagerService_ReleaseRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomManagerServiceServer).ReleaseRoom(ctx, req.(*ReleaseRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoomManagerService_ServiceDesc is the grpc.ServiceDesc for RoomManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoomManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "room_manager.RoomManagerService",
	HandlerType: (*RoomManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _RoomManagerService_Ping_Handler,
		},
		{
			MethodName: "GetRoomWorker",
			Handler:    _RoomManagerService_GetRoomWorker_Handler,
		},
		{
			MethodName: "PingWorker",
			Handler:    _RoomManagerService_PingWorker_Handler,
		},
		{
			MethodName: "RegisterRoom",
			Handler:    _RoomManagerService_RegisterRoom_Handler,
		},
		{
			MethodName: "ProlongRoom",
			Handler:    _RoomManagerService_ProlongRoom_Handler,
		},
		{
			MethodName: "ReleaseRoom",
			Handler:    _RoomManagerService_ReleaseRoom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "room_manager/room_manager.proto",
}
