// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: vocab_manager/vocab_manager.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_vocab_manager_vocab_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vocab_manager_vocab_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_vocab_manager_vocab_manager_proto_rawDescGZIP(), []int{0}
}

func (x *PingResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetAvailableVocabsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableVocabsResponse) Reset() {
	*x = GetAvailableVocabsResponse{}
	mi := &file_vocab_manager_vocab_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableVocabsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableVocabsResponse) ProtoMessage() {}

func (x *GetAvailableVocabsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vocab_manager_vocab_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableVocabsResponse.ProtoReflect.Descriptor instead.
func (*GetAvailableVocabsResponse) Descriptor() ([]byte, []int) {
	return file_vocab_manager_vocab_manager_proto_rawDescGZIP(), []int{1}
}

func (x *GetAvailableVocabsResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type GetVocabRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVocabRequest) Reset() {
	*x = GetVocabRequest{}
	mi := &file_vocab_manager_vocab_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVocabRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVocabRequest) ProtoMessage() {}

func (x *GetVocabRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vocab_manager_vocab_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVocabRequest.ProtoReflect.Descriptor instead.
func (*GetVocabRequest) Descriptor() ([]byte, []int) {
	return file_vocab_manager_vocab_manager_proto_rawDescGZIP(), []int{2}
}

func (x *GetVocabRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetVocabResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrimaryWords  []string               `protobuf:"bytes,1,rep,name=primary_words,json=primaryWords,proto3" json:"primary_words,omitempty"`
	RudeWords     []string               `protobuf:"bytes,2,rep,name=rude_words,json=rudeWords,proto3" json:"rude_words,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVocabResponse) Reset() {
	*x = GetVocabResponse{}
	mi := &file_vocab_manager_vocab_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVocabResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVocabResponse) ProtoMessage() {}

func (x *GetVocabResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vocab_manager_vocab_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVocabResponse.ProtoReflect.Descriptor instead.
func (*GetVocabResponse) Descriptor() ([]byte, []int) {
	return file_vocab_manager_vocab_manager_proto_rawDescGZIP(), []int{3}
}

func (x *GetVocabResponse) GetPrimaryWords() []string {
	if x != nil {
		return x.PrimaryWords
	}
	return nil
}

func (x *GetVocabResponse) GetRudeWords() []string {
	if x != nil {
		return x.RudeWords
	}
	return nil
}

var File_vocab_manager_vocab_manager_proto protoreflect.FileDescriptor

const file_vocab_manager_vocab_manager_proto_rawDesc = "" +
	"\n" +
	"!vocab_manager/vocab_manager.proto\x12\rvocab_manager\x1a\x1bgoogle/protobuf/empty.proto\"\x1e\n" +
	"\fPingResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"2\n" +
	"\x1aGetAvailableVocabsResponse\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"%\n" +
	"\x0fGetVocabRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"V\n" +
	"\x10GetVocabResponse\x12#\n" +
	"\rprimary_words\x18\x01 \x03(\tR\fprimaryWords\x12\x1d\n" +
	"\n" +
	"rude_words\x18\x02 \x03(\tR\trudeWords2\xf8\x01\n" +
	"\x13VocabManagerService\x12;\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x1b.vocab_manager.PingResponse\x12W\n" +
	"\x12GetAvailableVocabs\x12\x16.google.protobuf.Empty\x1a).vocab_manager.GetAvailableVocabsResponse\x12K\n" +
	"\bGetVocab\x12\x1e.vocab_manager.GetVocabRequest\x1a\x1f.vocab_manager.GetVocabResponseB.Z,github.com/xolra0d/alias-online/shared/protob\x06proto3"

var (
	file_vocab_manager_vocab_manager_proto_rawDescOnce sync.Once
	file_vocab_manager_vocab_manager_proto_rawDescData []byte
)

func file_vocab_manager_vocab_manager_proto_rawDescGZIP() []byte {
	file_vocab_manager_vocab_manager_proto_rawDescOnce.Do(func() {
		file_vocab_manager_vocab_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vocab_manager_vocab_manager_proto_rawDesc), len(file_vocab_manager_vocab_manager_proto_rawDesc)))
	})
	return file_vocab_manager_vocab_manager_proto_rawDescData
}

var file_vocab_manager_vocab_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_vocab_manager_vocab_manager_proto_goTypes = []any{
	(*PingResponse)(nil),               // 0: vocab_manager.PingResponse
	(*GetAvailableVocabsResponse)(nil), // 1: vocab_manager.GetAvailableVocabsResponse
	(*GetVocabRequest)(nil),            // 2: vocab_manager.GetVocabRequest
	(*GetVocabResponse)(nil),           // 3: vocab_manager.GetVocabResponse
	(*emptypb.Empty)(nil),              // 4: google.protobuf.Empty
}
var file_vocab_manager_vocab_manager_proto_depIdxs = []int32{
	4, // 0: vocab_manager.VocabManagerService.Ping:input_type -> google.protobuf.Empty
	4, // 1: vocab_manager.VocabManagerService.GetAvailableVocabs:input_type -> google.protobuf.Empty
	2, // 2: vocab_manager.VocabManagerService.GetVocab:input_type -> vocab_manager.GetVocabRequest
	0, // 3: vocab_manager.VocabManagerService.Ping:output_type -> vocab_manager.PingResponse
	1, // 4: vocab_manager.VocabManagerService.GetAvailableVocabs:output_type -> vocab_manager.GetAvailableVocabsResponse
	3, // 5: vocab_manager.VocabManagerService.GetVocab:output_type -> vocab_manager.GetVocabResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vocab_manager_vocab_manager_proto_init() }
func file_vocab_manager_vocab_manager_proto_init() {
	if File_vocab_manager_vocab_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vocab_manager_vocab_manager_proto_rawDesc), len(file_vocab_manager_vocab_manager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vocab_manager_vocab_manager_proto_goTypes,
		DependencyIndexes: file_vocab_manager_vocab_manager_proto_depIdxs,
		MessageInfos:      file_vocab_manager_vocab_manager_proto_msgTypes,
	}.Build()
	File_vocab_manager_vocab_manager_proto = out.File
	file_vocab_manager_vocab_manager_proto_goTypes = nil
	file_vocab_manager_vocab_manager_proto_depIdxs = nil
}
