// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: vocab_manager/vocab_manager.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VocabManagerService_Ping_FullMethodName               = "/vocab_manager.VocabManagerService/Ping"
	VocabManagerService_GetAvailableVocabs_FullMethodName = "/vocab_manager.VocabManagerService/GetAvailableVocabs"
	VocabManagerService_GetVocab_FullMethodName           = "/vocab_manager.VocabManagerService/GetVocab"
)

// VocabManagerServiceClient is the client API for VocabManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VocabManagerServiceClient interface {
	Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PingResponse, error)
	GetAvailableVocabs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAvailableVocabsResponse, error)
	GetVocab(ctx context.Context, in *GetVocabRequest, opts ...grpc.CallOption) (*GetVocabResponse, error)
}

type vocabManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVocabManagerServiceClient(cc grpc.ClientConnInterface) VocabManagerServiceClient {
	return &vocabManagerServiceClient{cc}
}

func (c *vocabManagerServiceClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, VocabManagerService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vocabManagerServiceClient) GetAvailableVocabs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAvailableVocabsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAvailableVocabsResponse)
	err := c.cc.Invoke(ctx, VocabManagerService_GetAvailableVocabs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vocabManagerServiceClient) GetVocab(ctx context.Context, in *GetVocabRequest, opts ...grpc.CallOption) (*GetVocabResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVocabResponse)
	err := c.cc.Invoke(ctx, VocabManagerService_GetVocab_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VocabManagerServiceServer is the server API for VocabManagerService service.
// All implementations must embed UnimplementedVocabManagerServiceServer
// for forward compatibility.
type VocabManagerServiceServer interface {
	Ping(context.Context, *emptypb.Empty) (*PingResponse, error)
	GetAvailableVocabs(context.Context, *emptypb.Empty) (*GetAvailableVocabsResponse, error)
	GetVocab(context.Context, *GetVocabRequest) (*GetVocabResponse, error)
	mustEmbedUnimplementedVocabManagerServiceServer()
}

// UnimplementedVocabManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVocabManagerServiceServer struct{}

func (UnimplementedVocabManagerServiceServer) Ping(context.Context, *emptypb.Empty) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedVocabManagerServiceServer) GetAvailableVocabs(context.Context, *emptypb.Empty) (*GetAvailableVocabsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAvailableVocabs not implemented")
}
func (UnimplementedVocabManagerServiceServer) GetVocab(context.Context, *GetVocabRequest) (*GetVocabResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVocab not implemented")
}
func (UnimplementedVocabManagerServiceServer) mustEmbedUnimplementedVocabManagerServiceServer() {}
func (UnimplementedVocabManagerServiceServer) testEmbeddedByValue()                             {}

// UnsafeVocabManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VocabManagerServiceServer will
// result in compilation errors.
type UnsafeVocabManagerServiceServer interface {
	mustEmbedUnimplementedVocabManagerServiceServer()
}

func RegisterVocabManagerServiceServer(s grpc.ServiceRegistrar, srv VocabManagerServiceServer) {
	// If the following call panics, it indicates UnimplementedVocabManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VocabManagerService_ServiceDesc, srv)
}

func _VocabManagerService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VocabManagerServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VocabManagerService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VocabManagerServiceServer).Ping(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VocabManagerService_GetAvailableVocabs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VocabManagerServiceServer).GetAvailableVocabs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VocabManagerService_GetAvailableVocabs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VocabManagerServiceServer).GetAvailableVocabs(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VocabManagerService_GetVocab_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVocabRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VocabManagerServiceServer).GetVocab(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VocabManagerService_GetVocab_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VocabManagerServiceServer).GetVocab(ctx, req.(*GetVocabRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VocabManagerService_ServiceDesc is the grpc.ServiceDesc for VocabManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VocabManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vocab_manager.VocabManagerService",
	HandlerType: (*VocabManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _VocabManagerService_Ping_Handler,
		},
		{
			MethodName: "GetAvailableVocabs",
			Handler:    _VocabManagerService_GetAvailableVocabs_Handler,
		},
		{
			MethodName: "GetVocab",
			Handler:    _VocabManagerService_GetVocab_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vocab_manager/vocab_manager.proto",
}
